### ISSUE TITLE
Icon overwritten by other extension

### ISSUE THREAD

**Issue by danieledep** [adamjkb/atom-font-icons#1]
This VSCode extension works great, thank you. 

The only thing breaking for me is the CSS icon which displays the Tailwind icon instead.

![Screenshot 2024-02-27 at 17 12 11](https://github.com/adamjkb/atom-font-icons/assets/9954596/b7e84a43-5376-4a1f-ba8a-d993c08bc9cd)

I saw that other icon themes don't get their icons overwritten, so I was wondering if maybe was possible to try to prevent this, thanks

**Comment by adamjkb** [comment]
interesting! this line should define the default icon for files:

https://github.com/adamjkb/atom-font-icons/blob/0301027ebce8d40e5d5a00d5053aec9242c078c9/fileicons/atom-font-icon-theme.json#L54

My guess is if there are other file icon themes installed that references file extensions that this package doesn't it could fall back to those and not the default icon in this package. I would start by looking into if you don't already have other file icon themes installed and disable them.

**Comment by danieledep** [comment]
Yes the extension it's the Tailwind Intellisense Extension, they added their icon in commit: [#794](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/794), if I disable it the correct icon show up.

**Comment by adamjkb** [comment]
That package is installed for me too but I don't get their icons. Could you try to go into your vscode extension and manually add a line about css, restart vscode and see if it fixes it?

The vscode extensions are normally located in:

```bash
~/.vscode/extensions/adamjkb.atom-font-icons-1.0.1/fileicons/atom-font-icon-theme.json
```

And add a line here:

```diff
"fileExtensions": {
+   "css":` "_file",
    "jpeg": "_file_media",
    "jpg": "_file_media"
    ...
```

**Comment by danieledep** [comment]
You are right, the Tailwind icon came up only after I associated .css files to the extension, to get support for custom at-rules and syntax highlighting, like this:
```
"files.associations": {
    "*.css": "tailwindcss"
},
```
Anyways your fix worked perfectly!

**Comment by adamjkb** [comment]
Thanks for flagging it! The build I just published should fix it permanently. :)
